name: docker-misc-${CONTAINER_NAME}
services:
  sonitranslate:
    image: ${CONTAINER_NAME}:latest
    container_name: ${CONTAINER_NAME}
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - ${HF_HOME}:/root/.cache/huggingface
      - ${TORCH_HOME}:/root/.cache/torch
    ports:
      - 8201:7860
    command: python app_rvc.py --public_url --theme SherlockRamos/Feliz
    tty: true
    environment:
      - YOUR_HF_TOKEN=${YOUR_HF_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
